# Generated by Django 5.2 on 2025-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="esp_id",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
