# Generated by Django 5.2 on 2025-04-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_sensordata_esp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensordata",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
