# Generated by Django 5.2 on 2025-04-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_rename_created_at_sensordata_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="location",
            field=models.CharField(default="Sandnes", max_length=100),
            preserve_default=False,
        ),
    ]
