# Generated by Django 5.2 on 2025-05-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0004_sensordata_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="battery",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
