# Generated by Django 5.2 on 2025-05-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0005_sensordata_battery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="battery",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
