# Generated by Django 5.2 on 2025-05-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0006_alter_sensordata_battery"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="battery_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
